#!/bin/bash

echo "=========================================================="
echo "📊 GOOGLE SEARCH CONSOLE - SUBMISSION TRACKER"
echo "=========================================================="
echo ""
echo "जो URLs submit हो चुके हैं उन्हें tick करें"
echo ""
echo "🥇 WEEK 1 (Top Priority) - आज/कल:"
echo ""
echo "   [ ] https://ravishankarkamal59-eng.github.io/"
echo "   [ ] https://ravishankarkamal59-eng.github.io/upsc.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/bpsc.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/ssc-cgl.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/railway.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/banking.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/notes.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/current-affairs.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/quiz.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/ai-chat.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/exams.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/nda-cds.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/bihar-police.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/exam-calendar.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/privacy.html"
echo ""
echo "🥈 WEEK 2 (Updates & Utility):"
echo ""
echo "   [ ] https://ravishankarkamal59-eng.github.io/admit-card.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/result.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/answer-key.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/notifications.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/scholarship.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/blog.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/about.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/contact.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/terms.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/faq.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/forum.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/pdf-viewer.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/quiz-advanced.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/bookmarks.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/dashboard.html"
echo ""
echo "🥉 WEEK 3 (SSC & UG/PG):"
echo ""
echo "   [ ] https://ravishankarkamal59-eng.github.io/ssc-chsl.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/ssc-mts.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/ssc-gd.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/jee-mains.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/neet.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/gate.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/bca-mca.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/llb.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/cat-mba.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/nursing.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/cuet.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/ba-ma.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/uppcs.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/mppsc.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/ras.html"
echo ""
echo "🏅 WEEK 4 (Special & State):"
echo ""
echo "   [ ] https://ravishankarkamal59-eng.github.io/jpsc.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/ukpsc.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/bihar-si.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/up-police.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/pet.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/b-ed.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/ctet.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/ugc-net.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/agta.html"
echo "   [ ] https://ravishankarkamal59-eng.github.io/up-lekhpal.html"
echo ""
echo "🏅 WEEK 5 (Notes Categories):"
echo ""
echo "   [ ] https://ravishankarkamal59-eng.github.io/notes-history.html" 2>/dev/null
echo "   [ ] (Notes categories अभी notes.html पर हैं)"
echo ""
echo "=========================================================="
echo "📝 निर्देश:"
echo "1. ऊपर दी गई list को कॉपी करके WhatsApp/Notes में save करें"
echo "2. जो URL submit करें, उसके आगे [✓] कर दें"
echo "3. हर दिन 5-7 URLs से ज्यादा न करें"
echo "4. 15 दिन में सभी 55 URLs submit हो जाएँगे"
echo "=========================================================="
